export const actionTypes = {
  INCREASE_COUNT: 'INCREASE_COUNT',
  DECREASE_COUNT: 'DECREASE_COUNT',
  RESET_COUNT: 'RESET_COUNT',
  FETCH_PROJECTS: 'FETCH_PROJECTS',
  FETCH_PROJECTS_SUCCESS: 'FETCH_PROJECTS_SUCCESS',
  FETCH_PROJECTS_ERROR: 'FETCH_PROJECTS_ERROR',
  FETCH_PROJECTS_DETAILS: 'FETCH_PROJECTS_DETAILS',
  FETCH_PROJECTS_DETAILS_SUCCESS: 'FETCH_PROJECTS_DETAILS_SUCCESS',
  FETCH_PROJECTS_DETAILS_ERROR: 'FETCH_PROJECTS_DETAILS_ERROR',
}
